// <auto-generated />
namespace EasyERP.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class user_addColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_addColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201607010610363_user_addColumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
